### PR TITLE
Features to save and reuse the trained models are now integrated

### PR DESCRIPTION
**Pull request by sanjaythakur**
The 'train.py' script now saves the model once the training has been completed which can be reused again at a later point in time.

### CODE REVIEW

**Comment by pat-coady** [comment]
Sanjay - very sorry for the delay. Can you describe any testing you did to check your improvements didn't break anything?

Thanks a lot, Pat

**Comment by sanjaythakur** [comment]
Hi Pat, the only changes I made in the code are
* saving the policy network after the prescribed training has completed,
* an additional script by the name of `reload.py` to show how to use those saved policy networks later.

Other than these two changes, I didn't change/modify any part of the existing code. So I don't think it should break anything. For validating the robustness, I have run `python train.py` from `src/` on all the MUJOCO environments except `Ant`, `Humanoid`, and `HumanoidStandup` (because they take a lot of time) over the last three days and then verified the saved models by running `reload.py`. Everything worked out well.

I hope this answers your question. Let me know if you think it needs more testing.

**Comment by pat-coady** [comment]
Looks good, merged. Nice addition, thanks a lot.

**Comment by pat-coady** [comment]
Sanjay -

Sorry, I had to revert this. I got errors when running locally. Also, new code doesn't have docstrings, seems to be indented with tabs and other PEP8 violations.

Some errors I saw on reload. Also, code created some unexpected files src directory.

from: can't read /var/mail/gym
./reload.py: line 8: syntax error near unexpected token `('
./reload.py: line 8: `def getScaleAndOffset(env_name):'

**Pull request merged**
